spring:
  application:
    name: ws-retail-orderservice
  devtools:
    livereload:
      enabled: true
  #  profiles:
  #    active : DEV

  data:
    mongodb:
      uri: mongodb://localhost:27017/reach-engine
      username: root
      password: rootpassword
      repositories:
        type: AUTO