spring:
  application:
    name: ws-retail-orderservice
  devtools:
    livereload:
      enabled: true
  #  profiles:
  #    active : DEV

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:27017/reach-engine
      username: root
      password: rootpassword
      authentication-database: admin
      repositories:
        type: AUTO

logging:
  level:
    org:
      mongodb=DEBUG: